// Code generated by "stringer -type=State"; DO NOT EDIT.

package bible

import "strconv"

const _State_name = "S_STARTS_BOOKS_CHAPTERS_VERSES_NEXT_NUMS_NEXT_VERSES_END"

var _State_index = [...]uint8{0, 7, 13, 22, 29, 39, 51, 56}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
