// Code generated by "stringer -type=Token"; DO NOT EDIT.

package bible

import "strconv"

const _Token_name = "ILLEGALBOOKNEXT_NUMCOMMADASHEOFWS"

var _Token_index = [...]uint8{0, 7, 11, 19, 24, 28, 31, 33}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
